### ISSUE TITLE
May be the incorrect translation? `deleting_tilemaps_will_delete_tilesets`

### ISSUE THREAD

**Issue by TakWolf** [lufog/aseprite-language-russian#10]
https://github.com/aseprite/aseprite/blob/eafb779ef063a6965340cbb2e9e1632aad88a7f9/data/strings/en.ini#L71-L77

https://github.com/lufog/aseprite-language-russian/blob/e28238e58f89befd2443ba9c272a079d6730c013/russian-language/ru.ini#L71-L77

https://github.com/aseprite/aseprite/pull/4156/files

**Comment by lufog** [comment]
Yes indeed, thank you! (ac1902450220b8b9900e13551c6724846e0ab0f7)
