### ISSUE TITLE
The translation of Aseprite has been migrated to Weblate.

### ISSUE THREAD

**Issue by TakWolf** [lufog/aseprite-language-russian#11]
Hi!

The translation of Aseprite has been migrated to Weblate.

Russian is here: https://hosted.weblate.org/projects/aseprite/aseprite/ru/

The latest node has been imported.

Please feel free to try. 
If any problem, please feel free to provide feedback at any time

**Comment by lufog** [comment]
Well, if Weblate is the only official place for user translations, then I'll probably set the repository to read-only mode and finish working on Russian translation. I have no desire to update or maintain translations on Weblate. If my translation was used as a source, it is not very nice act, as the lines containing authorship and license were removed.

**Comment by TakWolf** [comment]
Hi, I am not an official.

The migration work has just begin, and when the workflow is completed, the copyright line will be retained.
Would you like us to use the current translation? If you object, I will immediately request the deletion of the Russian translation. Importing is my personal behavior. I apologize for any possible offense.

**Comment by lufog** [comment]
I ask you to either add attribution as required by CC BY 4.0. Or start the translation from scratch, without using this repository as an import source. In any case, I am not ready to continue this translation anywhere other than this repository. Just like, I’m not ready to lose the history of commits from 2019 to the present day.

**Comment by TakWolf** [comment]
Aseprite still uses ini as the translation file, see: （Just changed the multi line format to single line format）

https://github.com/TakWolf/aseprite/blob/main/data/strings/en.ini
https://github.com/TakWolf/aseprite/blob/main/data/strings/ru.ini

The copyright line still appears on the first line as before. (As the workflow has not been completed yet, there is currently no content available.)

All the translation licensed by CC-BY-4.0
<img width="298" alt="image" src="https://github.com/lufog/aseprite-language-russian/assets/6064962/9caa0c64-9d15-4464-b437-ca1813cd7982">

The import is one-time, and all subsequent translation work will only be carried out on the weblate and there will be no external sources.

I don't want to offend anyone. But I feel your unhappiness. 
Importing is my personal behavior.
So I also want to confirm again, if you are willing for us to use the current translation?
Even if it meets the license, if you don't like it, I will delete it.
(Forgive my English.)

**Comment by lufog** [comment]
As long as authorship (`Copyright (C) 2019-2023  Aleksey Smirnov (aka lufog)`) is indicated in at least the translation file, I am not against its presence on Weblate. But I will not maintain this translation anywhere other than here. This is not a problem if there are other people on Weblate who will take over the maintenance.
