### ISSUE TITLE
Частичное отсутствие перевода

### ISSUE THREAD

**Issue by lolipodass** [lufog/aseprite-language-russian#2]
а именно осталься не переведен весь начальный экран, от создания нового файла, до новостей 
<details>
<summary>Скриншот</summary>
  
![image](https://user-images.githubusercontent.com/56706038/124323419-f73e7480-db89-11eb-8e01-a0f25bb0b757.png)
  
</details>

**Comment by lolipodass** [comment]
а так же я только что увидел что вы еще не перевели в настройках одну вещь
<details>
<summary>Скриншот</summary>
  
![image](https://user-images.githubusercontent.com/56706038/124324006-e4786f80-db8a-11eb-9723-f7ce8f0d232c.png)
  
</details>

**Comment by lufog** [comment]
Это версия 1.3 beta? Перевод для версии 1.3 будет сделан как только она выйдет из beta. В версии 1.2.27, последняя версия для которой доступен перевод, начальный экран в порядке.

<details>
  <summary>Скриншот</summary>
  
 ![image](https://user-images.githubusercontent.com/10379487/124367133-56b98480-dc5d-11eb-9486-b822c5e50df6.png)
  
</details>

Если ваша версия программы не 1.3. Проверьте есть ли у вас в папке `data\strings` файл `ru.ini`, если такой файл есть, удалите его. 

В новых версиях перевода, все файлы собраны в расширение `extensions\russian-language`, исключением является шрифт с кириллицей, который пока нет возможности загрузить не прибегая к подмене файлов приложения, или использованию тем. Сейчас с dacap ведется диалог о добавлении такой возможности, чтобы в будущем можно было обойтись вовсе без подмены файлов.

На счет второго скриншота, видимо этих строк пока нет в оригинальном языковом файле, возможно dacap забыл их туда вынести. Все переводы я делаю основываясь на оригинальном файле языка `en.ini`, если в нем нет каких-либо строк их не будет и в переводе.

Я собрал все места где нет перевода, и открыл issue (https://github.com/aseprite/aseprite/issues/2809) в репозитории Aseprite. Чтобы dacap добавил соответствующие строки в языковой файл. Если я что-либо пропустил, можете меня там дополнить.
