### ISSUE TITLE
Размытый шрифт

### ISSUE THREAD

**Issue by Den555By** [lufog/aseprite-language-russian#3]
У меня в программе, когда включаю русский язык, шрифт становится размытым и немного криво расположен по интерфейсу. Как исправлять?
![Снимок экрана 2022-04-30 170439](https://user-images.githubusercontent.com/41540074/166108836-1485a8ab-5e12-462f-959f-4945f2e18422.png)

**Comment by lufog** [comment]
Папку `data` из архива тоже нужно извлекать с заменой. В ней находится фикс для нормального отображения кириллицы.

**Comment by panaetovSS** [comment]
Размытый текст после установки помогите решить проблему не получается

**Comment by lufog** [comment]
@panaetovSS для версии 1.2 помимо установки расширения, нужно использовать фикс шрифта. Папку data из [архива](https://github.com/lufog/aseprite-language-russian/releases/tag/v1.2.40-v2) нужно извлечь в корневую папку программы, с заменой файлов. В [инструкции](https://github.com/lufog/aseprite-language-russian/blob/1.2/README.ru.md) все написано.
