### ISSUE TITLE
The Unified Languages Extension

### ISSUE THREAD

**Issue by TakWolf** [lufog/aseprite-language-russian#5]
Hi!

We are currently making a unified languages extension for aseprite. Project are:

https://github.com/aseprite-quest/aseprite-unified-languages-extension
https://github.com/aseprite-quest/aseprite-unified-pixel-theme

I have discovered the Russian extension here. We hope to use it as a basic translation for Russian. 

We made a diff util that can auto fill the missing rows from latest version "en.ini" with a "# TODO # " prefix. 
Like:

https://github.com/aseprite-quest/aseprite-unified-languages-extension/blob/1bf7fe32504d38ee3f5b37c059b4234bb0ce870f/data/ru.ini#L57

So that anyone can quickly and sporadically submit contributions.

Are there any issues? If there are any questions, please contact us at any time. And if you are interested in becoming a reviewer of Russian language contributions, I will send you an invitation.
https://github.com/aseprite-quest

Thanks!!!

**Comment by lufog** [comment]
I apologize for the late reply. Of course, I don't mind, you can use this translation in your project, just please keep the original copyright line.

**Comment by TakWolf** [comment]
Thank you for the permission!
There is a script auto pul the strings from this repository.
Thank you for your contribution!
