### ISSUE TITLE
Размытый текст 

### ISSUE THREAD

**Issue by panaetovSS** [lufog/aseprite-language-russian#9]
<img width="1728" alt="Снимок экрана 2023-11-19 в 00 15 43" src="https://github.com/lufog/aseprite-language-russian/assets/79225566/a8913c8d-029c-4ac7-a310-f72ad6d35002">
Пробывал много чего не помогает помогите )

**Comment by lufog** [comment]
@panaetovSS для версии 1.2.40 нужно качать [перевод для 1.2.40](https://github.com/lufog/aseprite-language-russian/releases/tag/v1.2.40-v2), в архиве помимо перевода есть фикс шрифта. 

Папку `data` из архива нужно извлечь в корневую папку программы, с заменой файлов. В [инструкции](https://github.com/lufog/aseprite-language-russian/blob/1.2/README.ru.md) процесс установки описан.

**Comment by panaetovSS** [comment]
попытался эти 2 файла заменить в папке fonts все осталась так же размытым

**Comment by lufog** [comment]
@panaetovSS, у меня нет Mac устройства, поэтому могу только предложить:

* файлы шрифта не были заменены, в App Bundle они находятся в `Contents/Resources/data/fonts`, убедитесь что заменяете эти файлы, файлами из фикса;
* используется нестандартная тема Aseprite, с вшитым шрифтом, не поддерживающим кириллицу, убедитесь что в Aseprite не используется сторонняя тема;
* это Mac специфичная проблема, которую я не могу диагностировать ввиду отсутствия у меня Mac устройства.

К слову, в Aseprite 1.3 шрифт поддерживает кириллицу из коробки, так что в крайнем случае можете попробовать эту версию. Перевод для версии 1.3 можно найти [здесь](https://github.com/lufog/aseprite-language-russian/releases/tag/v1.3-rc8).

**Comment by panaetovSS** [comment]
@lufog много чего пробывал все так же ,думаю останусь на теме eu потому что не вижу больше выхода , к слову я перешел недавно на мак , много времени сидел на windows , пока сложно освоиться на новом ОC я думаю с вашей программой все нормально , просто я что-то не правильно делаю .

**Comment by panaetovSS** [comment]
@lufog  можете меня поздравить у меня все получилось , проблема была конечно же что я криво все поставил )
